// Generated by CoffeeScript 1.8.0
(function() {
  var Scroller, TimePeriod;

  TimePeriod = function(assets) {
    this.assets = assets;
    this.mapPosition = null;
    return this.zoomLevel = null;
  };

  Scroller = function() {
    this.currentloction = null;
    this.buildLocation = function() {};
    this.zoom = false;
    this.init = function() {
      this.past = new TimePeriod(window._assets.past);
      this.present = new TimePeriod(window._assets.present);
      this.future = new TimePeriod(window._assets.future);
      this.currentloction = this.present;
      return this.buildLocation();
    };
    return this.init();
  };

  window.Scroller = Scroller;

  $(document).on('ready', function() {
    var $body, $container, $slider, currentTime, getSliderVal, moveLeft, moveRight, moveSlider;
    $body = $('body');
    $container = $('.container');
    $slider = $('#slider');
    currentTime = 'present';
    getSliderVal = function() {
      return $slider.slider('value');
    };
    $(document).on('keydown', function(e) {
      if (e.keyCode === 37) {
        moveLeft();
      }
      if (e.keyCode === 39) {
        return moveRight();
      }
    });
    $slider.slider({
      value: 50,
      min: 0,
      max: 99,
      animate: 400,
      step: 1,
      stop: function(e, ui) {
        return setTimeout(moveSlider, 10);
      }
    });
    moveLeft = function() {
      var value;
      value = getSliderVal() - 34;
      $slider.slider('value', value);
      return moveSlider();
    };
    moveRight = function() {
      var value;
      value = getSliderVal() + 34;
      $slider.slider('value', value);
      return moveSlider();
    };
    $(document).on('chicago.future', function(e) {
      $container.animate({
        opacity: 0
      }, 400, function() {
        return $container.css({
          backgroundImage: 'url(../img/future.jpg)'
        }).animate({
          opacity: 1
        }, 400);
      });
      return currentTime = 'future';
    });
    $(document).on('chicago.present', function(e) {
      $container.animate({
        opacity: 0
      }, 400, function() {
        return $container.css({
          backgroundImage: 'url(../img/present.jpg)'
        }).animate({
          opacity: 1
        }, 400);
      });
      return currentTime = 'present';
    });
    $(document).on('chicago.past', function(e) {
      $container.animate({
        opacity: 0
      }, 400, function() {
        return $container.css({
          backgroundImage: 'url(../img/past.jpg)'
        }).animate({
          opacity: 1
        }, 400);
      });
      return currentTime = 'past';
    });
    return moveSlider = function() {
      var value;
      value = getSliderVal();
      if (value > 66) {
        $slider.slider('value', 100);
        if (currentTime !== 'future') {
          return $(document).trigger('chicago.future');
        }
      } else if (value < 67 && value > 33) {
        $slider.slider('value', 50);
        if (currentTime !== 'present') {
          return $(document).trigger('chicago.present');
        }
      } else if (value <= 33) {
        $slider.slider('value', 0);
        if (currentTime !== 'past') {
          return $(document).trigger('chicago.past');
        }
      }
    };
  });

}).call(this);
